spring:
  datasource:
    url: postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: -spring-blog

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes